version: "3.2"
services:
  sql-server-db:
    container_name: codecord-api
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
